modLoader="javafml" #mandatory
loaderVersion="[35,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
[[mods]] #mandatory
modId="freezedup" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Freezd Up" #mandatory
credits="Coda (code) & Ninni (art)" #optional
authors="Team Draco" #optional
description='''
Placeholder description.'''
[[dependencies.wings]]
    modId="forge"
    mandatory=true
    versionRange="[32,)"
    ordering="NONE"
    side="BOTH"